/* Main.ino file generated by New Project wizard
 *
 * Created:   Ñá ×åð 18 2022
 * Processor: Arduino Mega
 * Compiler:  Arduino AVR (Proteus)
 */

// Peripheral Configuration Code (do not edit)
//---CONFIG_BEGIN---
#pragma GCC push_options
#pragma GCC optimize ("Os")

#include <core.h> // Required by cpu
#include <cpu.h>

#pragma GCC pop_options

// Peripheral Constructors
CPU &cpu = Cpu;

void peripheral_setup () {
}

void peripheral_loop() {
}
//---CONFIG_END---

const int buttonPin1 = 21;
const int buttonPin2 = 20;
const int buttonPin3 = 19;
byte val = 0;
const int enginePin = 49;

void setup () {
peripheral_setup();
// TODO: put your setup code here, to run once:
DDRL = 0xFF;
PORTL = 0;

DDRD = 0;
PORTD = 0xFF;

Serial.begin(9600); 
pinMode(buttonPin1, INPUT_PULLUP);
pinMode(buttonPin2, INPUT_PULLUP);
pinMode(buttonPin3, INPUT_PULLUP);
pinMode(enginePin, OUTPUT);
}

void loop() {
peripheral_loop();
// TODO: put your main code here, to run repeatedly:
if (digitalRead(buttonPin1) == LOW){
    val = 0xA1;
    Serial.write(0xA1);
    digitalWrite(enginePin, LOW);
    delay(50);
    }
if (digitalRead(buttonPin2) == LOW){
    val = 0xB1;
    Serial.write(0xB1);
    digitalWrite(enginePin, HIGH);
    delay(50);
    }
if (digitalRead(buttonPin3) == LOW){
    val = 0xC1;
    Serial.write(0xC1);
    delay(25);
    }
}
